// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2EylvFdjRKmTqwwHXZtY0rEsXsMCuhe0',
    appId: '1:1003409671089:web:a262827100b781e655b390',
    messagingSenderId: '1003409671089',
    projectId: 'bgmi-tournament-db5c1',
    authDomain: 'bgmi-tournament-db5c1.firebaseapp.com',
    storageBucket: 'bgmi-tournament-db5c1.firebasestorage.app',
    measurementId: 'G-9XJTN42VJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-1TCneTVOKwilX1_05lFl1HK7VVrm3Wk',
    appId: '1:1003409671089:android:5017d07feb72a73455b390',
    messagingSenderId: '1003409671089',
    projectId: 'bgmi-tournament-db5c1',
    storageBucket: 'bgmi-tournament-db5c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOpfCl5vFoF8tKU7A_EZL7DfOievuEwsk',
    appId: '1:1003409671089:ios:0e1ebb7f5004f8f055b390',
    messagingSenderId: '1003409671089',
    projectId: 'bgmi-tournament-db5c1',
    storageBucket: 'bgmi-tournament-db5c1.firebasestorage.app',
    iosBundleId: 'com.example.tournamentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOpfCl5vFoF8tKU7A_EZL7DfOievuEwsk',
    appId: '1:1003409671089:ios:0e1ebb7f5004f8f055b390',
    messagingSenderId: '1003409671089',
    projectId: 'bgmi-tournament-db5c1',
    storageBucket: 'bgmi-tournament-db5c1.firebasestorage.app',
    iosBundleId: 'com.example.tournamentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2EylvFdjRKmTqwwHXZtY0rEsXsMCuhe0',
    appId: '1:1003409671089:web:711476d2b6d4b3a955b390',
    messagingSenderId: '1003409671089',
    projectId: 'bgmi-tournament-db5c1',
    authDomain: 'bgmi-tournament-db5c1.firebaseapp.com',
    storageBucket: 'bgmi-tournament-db5c1.firebasestorage.app',
    measurementId: 'G-8Z94ZPCF4X',
  );
}
